#! /bin/bash

#Original idea by David Lutterkort http://watzmann.net/blog/2014/06/puppet-autosign-policy.html

PSK_DIR=/etc/puppetlabs/autosign/psk
PSK_DEFAULT=default.key

csr=$(< /dev/stdin)
certname=$1

echoerr() { echo "$@" 1>&2; }

# Get the certificate extension with OID $1 from the csr
function extension {
  echo "$csr" | openssl req -noout -text | fgrep -A1 "$1" | tail -n 1 \
      | sed -e 's/[^0-9a-zA-Z]*//'
}

psk=$(extension '1.3.6.1.4.1.34380.1.1.4')

if [ -z "${psk// }" ]; then
  echoerr "Empty psk in cert '$certname'"
  exit 1
fi

echo "autosign $1 with PSK $psk"

psk_file=$PSK_DIR/$certname
if [ ! -f "$psk_file" ]; then
    psk_file=$PSK_DIR/$PSK_DEFAULT
fi

if [ -f "$psk_file" ]; then
    if grep -Fxq "$psk" "$psk_file"; then
        exit 0
    else
        echoerr "File ('$psk_file') for '$psk' does not contain PSK from '$certname'"
        exit 1
    fi
else
    echoerr "Could not find PSK file and default PSK file for '$certname' ('$psk_file')"
    exit 1
fi
